apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: magomir
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sleep
        - '36000'
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"
