services:
  MagomirWonderHubServer:
    image: magomirwonderhub
    # build: ./docker/webserver/.
    container_name: MagomirWonderHubServer
    expose:
      - "23463"
    volumes:
      - HubData:/app/webpage/data
    restart: unless-stopped
  proxy:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - MagomirWonderHubServer
    restart: unless-stopped

volumes:
  HubData:
