FROM ubuntu:20.04

# Install dependencies
RUN apt update
RUN apt upgrade -y

# Install Python
RUN apt install software-properties-common -y 
RUN add-apt-repository ppa:deadsnakes/ppa -y 
RUN apt install python3.10 curl -y
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
# RUN apt install -y python3 python3-pip
# RUN apt install -y git
# RUN python -V
# RUN python3 -V
# RUN python3.10 -V
RUN pip3.10 install flask requests

RUN mkdir /app
# RUN git clone https://github.com/maciejsikora2302/MagomirWonderHub.git
COPY . /app/
# Download the source code

# Run the application
WORKDIR /app/webpage
CMD ["python3.10", "main.py"]
